=== l-Santiago-l/tecweb/practicas/p14/e4/serviciovod_ep.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT catalogoVod (cuenta, contenido)+>
<!ELEMENT cuenta (perfiles)>
<!ELEMENT perfiles (perfil)*>
<!ELEMENT contenido (peliculas, series)?>
<!ELEMENT peliculas (genero)+>
<!ELEMENT series (genero)+>
<!ELEMENT genero (titulo)+>
<!ELEMENT perfil (#PCDATA)>
<!ATTLIST cuenta correo CDATA #REQUIRED>
<!ATTLIST peliculas region (USA|ESP|ARG|KOR) "USA">
<!ATTLIST series region (MEX|USA|ESP|ARG|KOR) "USA">
<!ATTLIST perfil 
    usuario CDATA #REQUIRED
    idioma CDATA #REQUIRED
>
<!ATTLIST genero 
    nombre CDATA #REQUIRED
>
<!ELEMENT titulo (#PCDATA)>
<!ATTLIST titulo 
    duracion CDATA #REQUIRED
>

=== l-Santiago-l/tecweb/practicas/p14/e4/serviciovod4.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE catalogoVod SYSTEM "serviciovod_ep.dtd">
<catalogoVod>
    <cuenta correo="diego.leonh@alumno.buap.mx">
        <perfiles>
            <perfil usuario="Diego Henández" idioma="Español"></perfil>
            <perfil usuario="Santiago León" idioma="Español"></perfil>
        </perfiles>
    </cuenta>
    <contenido>
        <peliculas region="MEX">
            <genero nombre="Suspenso">
                <titulo duracion="127">Se7en</titulo>
                <titulo duracion="153">La sospecha</titulo>
                <titulo duracion="118">El silencio de los inocentes</titulo>
                <titulo duracion="104">Los otros</titulo>
            </genero>
            <genero nombre="Terror Psicologíco">
                <titulo duracion="90">Un lugar en silencio</titulo>
                <titulo duracion="135">Eso</titulo>
                <titulo duracion="81">El proyecto de la bruja de Blair</titulo>
                <titulo duracion="138">La isla siniestra</titulo>
            </genero>
        </peliculas>
        <series>
            <genero nombre="Caricaturas">
                <titulo duracion="20">Steven Universe</titulo>
                <titulo duracion="20">Hora de Aventura</titulo>
                <titulo duracion="20">Teen Titans</titulo>
                <titulo duracion="20">Pokemon</titulo>
            </genero>
            <genero nombre="Animé">
                <titulo duracion="21">Death Note</titulo>
                <titulo duracion="21">Shingeki no Kyojin</titulo>
                <titulo duracion="21">Kimentsu no Yaiba</titulo>
                <titulo duracion="21">Buko No Hero</titulo>
            </genero>
        </series>
    </contenido>
</catalogoVod>
